spring:
  liquibase:
    contexts: dev, faker
    parameters:
      csv_path: /app/config/data
  cloud:      
    consul:
      enabled: true
      host: consul.${vault.vps-host}
      port: 443
      scheme: https

      # TLS configuration
      tls:
        skip-verify: true


      # Consul Discovery (service registration/discovery)
      discovery:
        enabled: true
        service-name: ${SERVER_NAME}
        # prefer-ip-address: true
        ip-address: ${SERVER_NAME}.microservices.${vault.vps-host}
        port: 443
        instance-id: ${SERVER_NAME} 
        tags: urlprefix-/
        service-path: /
        scheme: https

        # Health check configuration
        health-check-path: /management/health
        health-check-interval: 15s
        health-check-tls-skip-verify: true

        # ACL token for discovery
        # acl-token: ${CONSUL_HTTP_TOKEN:}